# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d34481b7da502dba08707e4adacecafcceee54af3c3b47c633f91bed1ce32255f2770bd336752814acacf49a220bfbf8a0e2f23a40c8e88c0f8cae01ba733a75

test:
  secret_key_base: ac8d44047b88817eb2faafc96dd9ce0530f54cc4e36b149efa9db12cfbfd5a445321643844a849da2c4d985371c4713df52032e9b052fa1fad8e5f5aff01842a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
